### ISSUE TITLE
enlargeUUID() can be simplified

### ISSUE THREAD

**Issue by jonagoldman** [oculus42/short-uuid#35]
https://github.com/oculus42/short-uuid/blob/6171268f2dfe30b1880f2b2d1ff1127f5eeaff5f/index.js#L30-L45

can be simplified to:

```js
function enlargeUUID(shortId, translator) { 
    return translator(shortId).padStart(32, '0').replace(/^(.{8})(.{4})(.{4})(.{4})(.{12})/, '$1-$2-$3-$4-$5')
}
```

right?

**Comment by apptionlabs** [comment]
From README:
> short-uuid has been tested to work on Node 0.10.x and later


According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart, `padStart` was added in node 8.0.0 so would break for old versions.

**Comment by nojacko** [comment]
From README:

> short-uuid has been tested to work on Node 0.10.x and later

According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart, `padStart` was added in node 8.0.0 so would break for old versions.

**Comment by jonagoldman** [comment]
I think Node 8 is not longer maintained but I don't know, I use it in the browser.
