### ISSUE TITLE
How likely the translator.new() will generate the same uuid?

### ISSUE THREAD

**Issue by kempsteven** [oculus42/short-uuid#43]
Was wondering how likely will the `translator.new()` will generate same uuid? how safe is it using in a hundreds or thousands of item? if you have tested, in what percentage does it generate the same uuid? since its shortened, it will probably be less safe than the rfc compliant uuids.

**Comment by oculus42** [comment]
The value is shorter as a string because we use a larger alphabet than the hexadecimal of a UUID. Each generated value starts out as a standard RFC4122 v4-compliant UUID, using the [uuid](https://www.npmjs.com/package/uuid) library, and can be translated back into the original UUID If desired.

**Comment by kempsteven** [comment]
Alright got it thanks!
