### ISSUE TITLE
Customise Length of UUID 

### ISSUE THREAD

**Issue by cakesoft-shivani** [oculus42/short-uuid#55]
Can I put custom length of UUID ?

**Comment by oculus42** [comment]
You can provide a custom alphabet which will produce a different length of translation, but a [UUID is a specific format](https://tools.ietf.org/html/rfc4122), and short-uuid will always return to the UUID format, even if the value is shorter.

```javascript
const shortUUID = require('short-uuid');
const short = short(short.constants.flickrBase58, {consistentLength: false});

// Provide any length as long as it is hexadecimal
const s1 = short.fromUUID('12345'); // 'oaB'
const u1 = short.toUUID('oaB'); // '00000000-0000-0000-0000-000000012345'
```

If you want to translate another identifier format, I recommend using [any-base](https://www.npmjs.com/package/any-base) directly, which handles most of the translation in short-uuid. Something like this:

```javascript
const anyBase = require('any-base');

// Using short-uuid constant for Flickr, just for consistency in the examples
const baseHexToFlickr = anyBase(anyBase.HEX, short.constants.flickrBase58);
const baseFlickrToHex = anyBase(short.constants.flickrBase58, anyBase.HEX);

const s1 = baseHexToFlickr('12345'); // 'oaB'
const u1 = baseFlickrToHex('aoB'); // '12345'
```

**Comment by oculus42** [comment]
I am closing this issue, as it is answered. If you have additional questions on this, please feel free to reply.
