### ISSUE TITLE
Error on UC Browser

### ISSUE THREAD

**Issue by hungxp** [oculus42/short-uuid#61]
I using it in project nuxt js, but it don't working on UC browser. Error here 
` */
const shortenUUID = (longId, translator, paddingParams) => {
  const translated = translator(longId.toLowerCase().replace(/-/g, ''));

  if (!paddingParams || !paddingParams.consistentLength) return translated;

  return translated.padStart(
    paddingParams.shortIdLength,
    paddingParams.paddingChar,
  );
};`

**Comment by oculus42** [comment]
Can you provide more information around the error you experienced?

* What was the actual error that was reported?
* What version of UC Browser and on what platform/OS version?

Do you have `core-js` or polyfills for modern ES code?
My guess is that it may not support `.padStart` which was part of ES2017, but I do not have UC Browser to test.

**Comment by oculus42** [comment]
@hungxp Any followup on this? If you can provide the actual error message you received it would go a long way toward resolving the issue.

**Comment by hungxp** [comment]
UC Browser hasn't been updated for quite a while, maybe it doesn't support ES2017, I removed the library to be able to run on it
