### ISSUE TITLE
Provide format/validity checking functionality for hashed UUIDs

### ISSUE THREAD

**Issue by U-4-E-A** [oculus42/short-uuid#66]
Example - a UUID passed to the server by a user, I would like to be able to check it's validity. This would be based on alphabet used and length.

**Comment by oculus42** [comment]
@U-4-E-A After much too long, I am working on this for v5.2.

**Comment by U-4-E-A** [comment]
Thanks for implementing this feature.

It would be handy if there was also a function for validating full UUIDs. This can be done by utilising validate() from [uuid](https://www.npmjs.com/package/uuid). I am already implementing this myself in one of my packages but it would make things slightly cleaner if short-uuid I provided this functionality.

```
import short from 'short-uuid'
import { validate as UUIDValidate } from 'uuid'

export const isUUIDValid = (v: short.UUID | string): boolean => UUIDValidate(v)
```
